### ISSUE TITLE
pos0 in foam-extend version

### ISSUE THREAD

**Issue by ghost** [isoAdvector/isoAdvector#18]
Hi,

I am trying to install isoAdvector in foam-extend 5.0. 

The `pos0` function is not defined. When the functions are used, are they supposed to be  `s>= 0`  or just `s>0`? 

Additionally, are there any plans of having the new reconstruction methods for foam-extend? 

Best Regards

**Comment by roenby** [comment]
Hi Mamanunu

pos0 corresponds to s >= 0. See for instance [here](https://www.openfoam.com/documentation/guides/v2112/api/namespaceFoam.html#adfa872b182666fe2bd9ae429db3ae275).

Due to limited time and resources, there are no plans to systematically port new isoAdvector developments to foam-extend. 

In fact, even the OpenFOAM.org (foundation) version is now changing so rapidly in its API that it is not possible for me to keep the isoAdvector repository working with the latest .org versions.

Focus will therefore be on maintaining and further developing the isoAdvector version integrated in the OpenFOAM.com (OpenCFD) version.

Best,
Johan

**Comment by ghost** [comment]
Hi Dr.Roenby,

Thanks for the reply. 
For the version of FE in this repository to compile in FE-5.0, the `pos0` method does not exist. It is standard `pos` that accounts for s>=0.

Best Regards
