### ISSUE TITLE
Calculation on "ugly mesh" crashes in Foam::isoAdvection::timeIntegratedFlux()

### ISSUE THREAD

**Issue by MartinIsoz** [isoAdvector/isoAdvector#9]
Hello Johan,

first of all, thank you for all the work that you do on isoAdvector scheme. I would like to compare the results of the isoAdvector scheme to the results of MULES for complex geometries and thus ugly meshes.

I have a problem with running the cases - the isoAdvector crashes with the following:
`[1] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[1] #1  Foam::sigFpe::sigHandler(int) at ??:?
[1] #2  ? in "/lib/x86_64-linux-gnu/libc.so.6"
[1] #3  Foam::isoAdvection::timeIntegratedFlux() at ??:?
[1] #4  Foam::isoAdvection::advect() at ??:?
[1] #5  ? at ??:?
[1] #6  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
[1] #7  ? at ??:?`

both in single-core and parallel runs, OpenFOAM 4.1. Furthermore, I have some problems with reproducing the issue - the calculation crashes but not always at the same time (however, close enough).

If you would be interested, I could upload somewhere a small test case, where I encounter the error (approx 80MB due to the mesh). Unfortunately, I must admit that I am not so familiar with the isoAdvector scheme that I can rule out my own mistake during the case setup. However, the MULES calculation finishes without any troubles.

Best and once again, thank you for your contribution,
Martin

Ps: I took a quick look on the code. Please would it be possible for an isoFace with zero area to exist? I am asking due to the lines
`vector n0 = isoCutCell_.isoFaceArea();
n0 /= (mag(n0));`
in Foam::isoAdvection::timeIntegratedFlux()

**Comment by isoAdvector** [comment]
Hi MartinIsoz

Thank you very much for your feedback. Please send me the case and I'll have a look. You can use wetransfer.com. My e-mail is johan.roenby followed by @ and then gmail.com.

Cheers,
Johan

**Comment by isoAdvector** [comment]
Hi Martin

Thanks for the case setup files.

Just to be sure I understand before I look into your case: Did the
additions of SMALL to the denominators solve all your crash issues?

I don't think the addition of SMALL will lead to excessive errors. Of
course you'll have to check but it is perfectly normal stabilisation
practice in OpenFOAM.

If it works, I don't think there is more for me to do here except maybe add
SMALL stabilisation in the isoAdvector repo :-)

A small thing: Shouldn't it say n0 /= (mag(n0) + SMALL) rather than n0 /=
(mag(n0+SMALL))? Seems you are adding a vector and a scalar.

Best,
Johan





2017-08-29 10:47 GMT+02:00 Martin Isoz <notifications@github.com>:

**Comment by MartinIsoz** [comment]
Hi Johan,

yes, the addition of SMALL indeed helped. The test case I sent you is currently running for a day or so. Another test case (which forced me to modify the timeIntegratedFaceFlux) is running for more than two days.

Yes, you are correct with the parantheses, I made a typo when rewriting the line.

As for the mistake brought into the calculation. Let me just think out loud (out written). I would be cautious about calculations on fine meshes with OpenFOAM compiled in single precision (however, does anyone actually do that?). I think that SMALL for single precision is 1e-8, which is the order of magnitude of magSf obtainable for a uniform orthogonal mesh with dX ~ 0.1 mm. Nevertheless, for my cases the addition of SMALL into denominators does not seem to qualitatively change the solution (see the attached images, on slices I depicted the cells with \alpha \in (0.001,0.999)).

Thank you for the swift communication, from my point of view this issue can be closed.

Best,
Martin

![compisoadvectormulespackingv3](https://user-images.githubusercontent.com/2018377/29960360-9964663c-8efb-11e7-84f0-c0c38344d519.png)
![compisoadvectormulestextplatev2cr](https://user-images.githubusercontent.com/2018377/29960361-9965ceb4-8efb-11e7-9784-f85a74d31daf.png)

**Comment by isoAdvector** [comment]
Hi Martin

Thanks for the response and the pics. Looks good!

I think most people compile with double precision so SMALL = 1e-15, which
should be OK in most practical simulations (faces smaller than 1e-8 m
linear scale have area smaller than 1e-15 so nano scale simulations using
meters as units would be a problem).

I did not include this kind of stabilization so far because obviously it
ruins the nice machine precision volume conservation of the idealized pure
advection test cases included with the code.

But now that the code is actually being used for real stuff, I think it is
time to include it.

I would prefer to do something like n0/max(SMALL,mag(n0)) or catch the
almost zero length normal vector more consistently in the procedure.

But for now, I think this is a good workaround for practical cases. I will
include it soon in a new commit.

Please do not hesitate to let me know if it crashes again.

Best,
Johan

2017-09-01 10:01 GMT+02:00 Martin Isoz <notifications@github.com>:
